IF OBJECT_ID('KERDES', 'U') IS NOT NULL DROP TABLE KERDES;
IF OBJECT_ID('VALASZ', 'U') IS NOT NULL DROP TABLE VALASZ;
IF OBJECT_ID('FELHASZNALOIADATOK', 'U') IS NOT NULL DROP TABLE FELHASZNALOIADATOK;
IF OBJECT_ID('LEADOTTVALASZ', 'U') IS NOT NULL DROP TABLE LEADOTTVALASZ;
IF OBJECT_ID('KUTATAS', 'U') IS NOT NULL DROP TABLE KUTATAS;
--IF OBJECT_ID('ISKOLAIVEGZETTSEG', 'U') IS NOT NULL DROP TABLE ISKOLAIVEGZETTSEG;
CREATE TABLE KUTATASOK 
    (KUTATASNEV           VARCHAR(50) NOT NULL, -- elsődleges kulcs, nem lehet 2 egyforma kutatás név.
     KEZDODATE            DATETIME,
     VEGZODATE            DATETIME,
     FOLIMIT              NUMERIC(2) NOT NULL, --max 99 fő, minimum 1
	 KUTATASLOCK          BIT NOT NULL, --Kezdő dátum elérés után nem szabad módosítani. Ezért zárolni kell.
CONSTRAINT KUTATASNEV_PRIMARY_KEY PRIMARY KEY (KUTATASNEV));

CREATE TABLE KERDESEK 
    (KERDESID              NUMERIC(5) NOT NULL, --NOT NULL PRIMARY KEY,
	 KUTATASNEV            VARCHAR(50) NOT NULL,
     LEIRAS                VARCHAR(100),
CONSTRAINT KERDES_PRIMARY_KEY PRIMARY KEY (KERDESID),
CONSTRAINT KUTATASNEV_FOREIGN_KEY FOREIGN KEY (KUTATASNEV) REFERENCES KUTATASOK (KUTATASNEV));--nem szükséges primary keyt így megadni, de jobban követhető.

CREATE TABLE VALASZOK
    (KERDESID              NUMERIC(5) NOT NULL,
	 VALASZID              NUMERIC(5) NOT NULL, -- csak a leírást tárolni a leadott válaszokban problémát okozna.
     LEIRAS                VARCHAR(50),
CONSTRAINT VALASZT_PRIMARY_KEY PRIMARY KEY (VALASZID),
CONSTRAINT KERDESID_FOREIGN_KEY FOREIGN KEY (KERDESID) REFERENCES KERDESEK (KERDESID));

CREATE TABLE FELHASZNALOIADATOK 
    (EMAIL              		  VARCHAR(50) NOT NULL,
     NEM                 		  VARCHAR(5) DEFAULT 'Férfi' CHECK (NEM='Férfi' OR NEM='Nő'), --lehetne bool, Enumerableval pedig Férfi/Nő
	 KOR                 		  NUMERIC(2) NOT NULL, -- Check fölösleges, mivel a program kód alapján szabható meg a kor.
	 VEGZETTSEG              	  VARCHAR(25) NOT NULL, -- lehetne külön listában.
CONSTRAINT EMAIL_PRIMARY_KEY PRIMARY KEY (EMAIL));

CREATE TABLE LEADOTTVALASZOK 
    (LEADOTTID             NUMERIC(5) NOT NULL,
	 EMAIL                 VARCHAR(50) NOT NULL,
	 KERDESID              NUMERIC(5) NOT NULL,
	 VALASZID              NUMERIC(5) NOT NULL,
--CONSTRAINT EMAIL PRIMARY KEY (EMAIL),
CONSTRAINT LEADOTT_PRIMARYKEY PRIMARY KEY(LEADOTTID), -- Kötelező csinálni kulcsot Entity miatt, forrás: stackoverflow.com LINK: https://stackoverflow.com/questions/14216995/the-table-view-does-not-have-a-primary-key-defined
CONSTRAINT LEADOTTEMAIL_FOREIGN_KEY FOREIGN KEY (EMAIL) REFERENCES FELHASZNALOIADATOK (EMAIL),
CONSTRAINT LEADOTTVALASZ_FOREIGN_KEY FOREIGN KEY (VALASZID) REFERENCES VALASZOK (VALASZID),
CONSTRAINT LEADOTTKERDESID_FORE1GN_KEY FOREIGN KEY (KERDESID) REFERENCES KERDESEK (KERDESID));