//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KözvelemenyKutatas
{
    using System;
    using System.Collections.Generic;
    
    public partial class KERDESEK
    {
        public KERDESEK()
        {
            this.VALASZOKs = new HashSet<VALASZOK>();
            this.LEADOTTVALASZOKs = new HashSet<LEADOTTVALASZOK>();
        }
    
        public decimal KERDESID { get; set; }
        public string KUTATASNEV { get; set; }
        public string LEIRAS { get; set; }
    
        public virtual ICollection<VALASZOK> VALASZOKs { get; set; }
        public virtual KUTATASOK KUTATASOK { get; set; }
        public virtual ICollection<LEADOTTVALASZOK> LEADOTTVALASZOKs { get; set; }
    }
}
