//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KözvelemenyKutatas
{
    using System;
    using System.Collections.Generic;
    
    public partial class KUTATASOK
    {
        public KUTATASOK()
        {
            this.KERDESEKs = new HashSet<KERDESEK>();
        }
    
        public string KUTATASNEV { get; set; }
        public Nullable<System.DateTime> KEZDODATE { get; set; }
        public Nullable<System.DateTime> VEGZODATE { get; set; }
        public decimal FOLIMIT { get; set; }
        public bool KUTATASLOCK { get; set; }
    
        public virtual ICollection<KERDESEK> KERDESEKs { get; set; }
    }
}
