//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KözvelemenyKutatas
{
    using System;
    using System.Collections.Generic;
    
    public partial class LEADOTTVALASZOK
    {
        public decimal LEADOTTID { get; set; }
        public string EMAIL { get; set; }
        public decimal KERDESID { get; set; }
        public decimal VALASZID { get; set; }
    
        public virtual FELHASZNALOIADATOK FELHASZNALOIADATOK { get; set; }
        public virtual KERDESEK KERDESEK { get; set; }
        public virtual VALASZOK VALASZOK { get; set; }
    }
}
