//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int Id { get; set; }
        public int PlayerId { get; set; }
        public int CharacterId { get; set; }
        public int MapId { get; set; }
        public int SkillRating { get; set; }
    
        public virtual Character Character { get; set; }
        public virtual Map Map { get; set; }
        public virtual Player Player { get; set; }
    }
}
