//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisGepKolcsonzoXKQCNV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gep
    {
        public Gep()
        {
            this.Kolcsonzes = new HashSet<Kolcsonze>();
        }
    
        public int Id { get; set; }
        public string Nev { get; set; }
        public int KolcsonzesAra { get; set; }
    
        public virtual ICollection<Kolcsonze> Kolcsonzes { get; set; }
    }
}
