//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KisGepKolcsonzoXKQCNV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kolcsonze
    {
        public int Id { get; set; }
        public int UgyfelId { get; set; }
        public int GepId { get; set; }
        public int NapokSzama { get; set; }
    
        public virtual Gep Gep { get; set; }
        public virtual Ugyfel Ugyfel { get; set; }
    }
}
