//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Xml;
using System.Xml.Serialization;
namespace KisGepKolcsonzoXKQCNV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ugyfel
    {
        public Ugyfel()
        {
            this.Kolcsonzes = new HashSet<Kolcsonze>();
        }
        public int Id { get; set; }
        public string Nev { get; set; }
        public string Cim { get; set; }
        public Nullable<int> Kedvezmeny { get; set; }
    
        public virtual ICollection<Kolcsonze> Kolcsonzes { get; set; }
    }
}
